### ISSUE TITLE
Reset method

### ISSUE THREAD

**Issue by toniengelhardt** [hidekatsu-izuno/nuxt-history-state#9]
Is there a way to completely reset the historyState on page reload so that _items gets cleared and page starts at 1 again?

**Comment by hidekatsu-izuno** [comment]
Thank you for your question. But it's difficult.

Because the page numbers are stored in the history API state. The history state values cannot be deleted.

However you can delete a history data at the page by using a clearItemData method.

**Comment by toniengelhardt** [comment]
Thanks for clarification @hidekatsu-izuno!
